// clazz
export const SET_CLAZZ_INFO = 'SET_CLAZZ_INFO'
export const GET_CLAZZ_DATA = 'GET_CLAZZ_DATA'

//department
export const SET_DEPARTMENT_INFO = 'SET_DEPARTMENT_INFO'
export const SET_DEPARTMENT_DATA = 'SET_DEPARTMENT_DATA'